[colors.normal]
black = "0x123e7c"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x123e7c"
magenta = "0xf003fc"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.bright]
black = "0x1c61c2"
red = "0xff0000"
green = "0xd300c4"
yellow = "0xf57800"
blue = "0x00ff00"
magenta = "0x711c91"
cyan = "0x0abdc6"
white = "0xd7d7d5"

[colors.primary]
background = "0x000b1e"
foreground = "0x0abdc6"

[window]
opacity = 0.8
class = { instance = "Alacritty", general = "Alacritty" }

[cursor]
style = { shape="Underline", blinking="On" }
blink_interval = 700
blink_timeout = 15

[font]
size = 8
normal = {family = "JetBrains Mono", style = "Regular"}

[shell]
program = "/bin/zsh"
args = ["-1"]
