[colors.bright]
black = "0x969896"
red = "0xe66861"
green = "0x53d585"
yellow = "0xffc668"
blue = "0x81a8ff"
magenta = "0xd89ffd"
cyan = "0x86f6ff"
white = "0xffffff"

[colors.normal]
black = "0x1d1f21"
red = "0xcc342b"
green = "0x198844"
yellow = "0xfba922"
blue = "0x3971ed"
magenta = "0xa36ac7"
cyan = "0x00ddee"
white = "0xc5c8c6"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[window]
opacity = 0.9

[font]
size = 8
normal = {family = "JetBrains Mono", style = "Regular"}
