format = """
 [](fg:#55ccfc inverted)\
$username[@](bg:#55ccfc fg:blue bold)$hostname\
[](bg:#f7a8d8 fg:#55ccfc)\
$cmd_duration\
[](bg:#ffffff fg:#f7a8d8)\
$sudo\
[](bg:#f7a8d8 fg:#ffffff)\
$directory\
[](bg:#55ccfc fg:#f7a8d8)\

$character
"""
continuation_prompt = "[  󱞩 ](bright-green)"


# Don't print a new line at the start of the prompt
add_newline = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# stuff for directory
[directory]
truncation_length = 4
truncation_symbol = '…/'
truncate_to_repo = false
style = "blue bold bg:#f7a8d8"
read_only_style = "red bold bg:#f7a8d8"
format = "[ $path]($style)[ $read_only]($read_only_style)"

[character]
success_symbol = "[](fg:#55ccfc)"
error_symbol = "[](fg:#55ccfc)"

[username]
style_user = 'bg:#55ccfc fg:blue bold'
style_root = 'bg:#55ccfc fg:blue bold'
format = '[$user]($style)'
disabled = false
show_always = true
aliases = { "root" = "super user" } 

[hostname]
ssh_only = false
format = '[$hostname](bold fg:blue bg:#55ccfc)'
disabled = false

[sudo]
style = 'bold blue bg:#ffffff'
format = '[ $symbol ]($style)'
symbol = '󰴅'
disabled = false

[cmd_duration]
min_time = 1000
format = '[ took $duration](italic blue bg:#f7a8d8)'
